site_name: Tastebuddy Documentation
site_url: https://docs.tastebuddy.io
copyright: Copyright &copy; 2024 Gautier Heins

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.footer
    - content.tooltips
  icon:
    logo: material/library-shelves
  favicon: images/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: teal
      accent: deep orange
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: teal
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: deep orange
extra_css:
  - stylesheets/extra.css

plugins:
  - privacy
  - search
  - open-in-new-tab
  - glightbox

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - For admins:
      - admin/index.md
      - User management: admin/user_administration.md
      - Products: admin/products.md
      - Tasting protocols: admin/protocols.md
  - For users:
      - user/index.md
      - Manageing your profile: user/profile.md
      - Evaluate samples: user/tasting.md
  - Result analysis:
      - results/index.md
      - Dashboards: results/dashboards.md
      - Reading the charts: results/charts.md
