site_name: Tastebuddy Documentation
site_url: https://docs.tastebuddy.io
copyright: Copyright &copy; 2024 Gautier Heins

theme:
  name: material
  custom_dir: overrides
  features:
    - content.tooltips
    - content.code.annotate
    - header.autohide
    - announce.dismiss
    - navigation.indexes
    - navigation.footer
  icon:
    logo: material/library-shelves
  favicon: images/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: teal
      accent: deep orange
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: teal
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: deep orange
extra_css:
  - stylesheets/extra.css

plugins:
  - privacy
  - search
  - open-in-new-tab
  - glightbox
  - material-plausible

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra:
  analytics:
    provider: plausible
    domain: docs.tastebuddy.io
    src: "http://plausible-twsg400wwcgk4swsgkwk0wko.49.13.76.205.sslip.io/js/plausible.js"
#
nav:
  - Home: index.md
  - For admins:
      - admin/index.md
      - User management: admin/user_administration.md
      - Products: admin/products.md
      - Tasting protocols: admin/protocols.md
  - For users:
      - user/index.md
      - Manage your profile: user/profile.md
      - Evaluate samples: user/tasting.md
  - Result analysis:
      - results/index.md
      - Dashboards: results/dashboards.md
      - Reading the charts: results/charts.md
      - Case study: results/use-cases.md
